### PR TITLE
Basic validations

### PR DESCRIPTION
**Pull request by fullcolorcoder**
Satisfies [MWPW-142966](https://jira.corp.adobe.com/browse/MWPW-142966)

In app.jsx, to test you can comment out 

```
      // const questionsData = await fetchFile(importBaseUrl, 'questions.json');
      // const stringsData = await fetchFile(importBaseUrl, 'strings.json');
```

And change to localhost for quick testing.

```
      const questionsData = await fetchFile('http://localhost:5173/src/assets/json/', 'questions.json');
      const stringsData = await fetchFile('http://localhost:5173/src/assets/json/', 'strings.json');
```

### CODE REVIEW

**Review by JackySun9 — APPROVED** [review]
looks great

**Comment by JackySun9** [comment]
Screenshot 2024-03-02 at 12 23 58 PM

not able to load the page

**Review by echampio-at-adobe — APPROVED** [review]

**Comment by echampio-at-adobe** [comment]
Found a bunch of errors in https://www.stage.adobe.com/products/photoshop/plan-recommender/

If we can generate a list of the missing combinations, it would likely help Walter. 
Screenshot 2024-03-04 at 3 02 23 PM

Now that I try and look at the sources, I'm not sure what the problems is with q5-ind. As far as I can see, all the questions are represented in strings. 

https://www.[stage.adobe.com/products/photoshop/plan-recommender/strings.json](https://www.stage.adobe.com/products/photoshop/plan-recommender/strings.json)

**Comment by fullcolorcoder** [comment]
@echampio-at-adobe Thank you for that catch. I refactored to more accurately compare, the JSON isn't generated exactly the same every time it appears. Should see green boxes now.

**Pull request merged**
